obstacle_range: 1.0
raytrace_range: 1.5
robot_radius: 0.22
inflation_radius: 0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.01
observation_sources: scan
scan: {sensor_frame: camera_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: true, expected_update_rate: 0}
